#!/usr/bin/env python3
"""Generate the icon set from icons.toml and a vendored upstream checkout.

One manifest produces everything, so the set, the code, the sprite and the
documentation cannot disagree with each other:

  crates/core/src/icons/generated.rs   symbol bodies, names, flags
  docs/src/reference/icons.md          the browsable index
  crates/core/NOTICE                   the upstream licence

Run it after editing icons.toml, and commit the result. CI regenerates and fails
on drift, so the committed output cannot rot.

Usage: python3 scripts/gen-icons.py [path-to-lucide-static-package]
"""

from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "icons.toml"
OUT_RS = ROOT / "crates" / "core" / "src" / "icons" / "generated.rs"
OUT_DOC = ROOT / "docs" / "src" / "reference" / "icons.md"
OUT_NOTICE = ROOT / "crates" / "core" / "NOTICE"

DEFAULT_UPSTREAM = Path("/tmp/lucide/package")


def body_of(svg: str) -> str:
    """The drawing instructions, stripped of the wrapper.

    Presentation attributes are deliberately dropped: an attribute on the symbol
    beats anything the use site inherits and cannot be reached by page CSS, so a
    consumer could never restyle the stroke. The outer element owns all of that.
    """
    inner = svg[svg.index(">", svg.index("<svg")) + 1 : svg.rindex("</svg>")]
    inner = re.sub(r"<!--.*?-->", "", inner, flags=re.S)
    # Collapse the pretty-printing; the sprite is not read by people.
    inner = re.sub(r"\s+", " ", inner).strip()
    return inner


def const_name(icon: str) -> str:
    return icon.upper().replace("-", "_")


def main() -> int:
    upstream = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_UPSTREAM
    if not (upstream / "icons").is_dir():
        print(
            f"no upstream at {upstream}.\n"
            "Fetch it with:\n"
            "  cd /tmp && npm pack lucide-static@<version> && tar xzf lucide-static-*.tgz\n"
            "then pass /tmp/package",
            file=sys.stderr,
        )
        return 2

    manifest = tomllib.loads(MANIFEST.read_text())
    version = manifest["upstream_version"]
    groups = [(k, v) for k, v in manifest.items() if isinstance(v, dict)]

    # Flags are comments in the manifest, so read them from the raw text: the
    # alternative is a nested table per icon, which would triple the file's
    # length for two booleans.
    raw = MANIFEST.read_text()
    fillable = set(re.findall(r'"([a-z0-9-]+)",\s*#[^\n]*fillable', raw))
    mirror = set(re.findall(r'"([a-z0-9-]+)",\s*#[^\n]*mirror', raw))

    icons: list[tuple[str, str, str]] = []  # (name, group, body)
    missing = []
    for group, data in groups:
        for name in data["icons"]:
            path = upstream / "icons" / f"{name}.svg"
            if not path.exists():
                missing.append(name)
                continue
            icons.append((name, group, body_of(path.read_text())))
    if missing:
        print(f"not in upstream {version}: {', '.join(missing)}", file=sys.stderr)
        return 1

    icons.sort()

    # ---- Rust ----------------------------------------------------------
    rs = [
        "// @generated by scripts/gen-icons.py from icons.toml. Do not edit.",
        f"// Upstream: lucide {version} (ISC). See crates/core/NOTICE.",
        "",
        "/// One icon in the framework's set.",
        "pub struct Icon {",
        "    /// The name an author writes in a descriptor.",
        "    pub name: &'static str,",
        "    /// Which group it belongs to in the documented index.",
        "    pub group: &'static str,",
        "    /// The drawing instructions, without an `svg` wrapper or any",
        "    /// presentation attributes: the render site owns those.",
        "    pub body: &'static str,",
        "    /// Whether filling it reads as a state rather than a blob.",
        "    pub fillable: bool,",
        "    /// Whether its direction carries meaning and flips under RTL.",
        "    pub mirror: bool,",
        "}",
        "",
        f"/// Every icon the framework ships, sorted by name. {len(icons)} of them.",
        f"pub static ICONS: [Icon; {len(icons)}] = [",
    ]
    for name, group, body in icons:
        rs.append("    Icon {")
        rs.append(f'        name: "{name}",')
        rs.append(f'        group: "{group}",')
        rs.append(f'        body: r##"{body}"##,')
        rs.append(f"        fillable: {str(name in fillable).lower()},")
        rs.append(f"        mirror: {str(name in mirror).lower()},")
        rs.append("    },")
    rs.append("];")
    rs.append("")
    rs.append("/// Every icon name as a constant, so the framework's own uses are")
    rs.append("/// checked by the compiler rather than by a test.")
    rs.append("pub mod names {")
    for name, _, _ in icons:
        rs.append(f'    pub const {const_name(name)}: &str = "{name}";')
    rs.append("}")
    OUT_RS.parent.mkdir(parents=True, exist_ok=True)
    OUT_RS.write_text("\n".join(rs) + "\n")

    # ---- Docs ----------------------------------------------------------
    doc = [
        "<!-- @generated by scripts/gen-icons.py from icons.toml. Do not edit. -->",
        "",
        "# Icons",
        "",
        f"The framework ships **{len(icons)} icons**. Name one in any descriptor that",
        "takes an `icon`: a settings item, a navigation entry, a resource.",
        "",
        "```rust,ignore",
        'SettingsItem::new("acme.blog", "Blog", fields).icon("newspaper")',
        "```",
        "",
        "An unknown name is refused when the application boots, with the nearest",
        "matches suggested, so a typo is caught before anybody sees a wrong glyph.",
        "",
        "## Adding one that is not here",
        "",
        "The set is curated rather than exhaustive: upstream ships over two thousand",
        "glyphs, and shipping all of them would cost every consumer to serve almost",
        "nobody. A plugin registers what it needs:",
        "",
        "```rust,ignore",
        "registry.add_icon(IconReg::new(",
        '    "map-pin-house",',
        '    include_str!("../assets/icons/map-pin-house.svg"),',
        "));",
        "```",
        "",
        "It is namespaced to your module automatically, so two plugins cannot",
        "collide, and you reference it as `vendor.package:map-pin-house`.",
        "",
        "## Flags",
        "",
        "**Fillable** icons are closed shapes that read correctly filled, which is how",
        "a state is shown: a filled star means favourited. Filling is a render option,",
        "never part of the name, so there is no `star-solid`.",
        "",
        "**Mirrored** icons flip under a right-to-left layout because their direction",
        "carries meaning. A clock does not mirror; a chevron does.",
        "",
    ]
    by_group: dict[str, list[tuple[str, str, str]]] = {}
    for item in icons:
        by_group.setdefault(item[1], []).append(item)
    for group, data in groups:
        entries = by_group.get(group, [])
        doc.append(f"## {group} ({len(entries)})")
        doc.append("")
        doc.append("| | Name | |")
        doc.append("| --- | --- | --- |")
        for name, _, body in entries:
            svg = (
                '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" '
                'stroke="currentColor" stroke-width="2" stroke-linecap="round" '
                f'stroke-linejoin="round">{body}</svg>'
            )
            flags = []
            if name in fillable:
                flags.append("fillable")
            if name in mirror:
                flags.append("mirrors in RTL")
            doc.append(f"| {svg} | `{name}` | {', '.join(flags)} |")
        doc.append("")
    OUT_DOC.parent.mkdir(parents=True, exist_ok=True)
    OUT_DOC.write_text("\n".join(doc))

    # ---- Notice --------------------------------------------------------
    licence = (upstream / "LICENSE").read_text().strip()
    OUT_NOTICE.write_text(
        "Third-party notices for laterite-core\n"
        "=====================================\n\n"
        "This crate compiles the following third-party work into the binaries\n"
        "that use it. Its licence is reproduced in full below.\n\n"
        "An application that distributes a built binary carries this work too.\n"
        "Tooling that gathers licences from dependencies finds this file by name\n"
        "and folds it into your notice automatically.\n\n\n"
        "Icons\n"
        "-----\n\n"
        f"Lucide {version} (a curated subset, {len(icons)} glyphs)\n"
        "    https://github.com/lucide-icons/lucide\n\n"
        f"{licence}\n"
    )

    print(
        f"{len(icons)} icons in {len(groups)} groups -> "
        f"{OUT_RS.relative_to(ROOT)}, {OUT_DOC.relative_to(ROOT)}, "
        f"{OUT_NOTICE.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
