// @generated by scripts/gen-icons.py from icons.toml. Do not edit.
// Upstream: lucide 1.46.0 (ISC). See crates/core/NOTICE.

/// One icon in the framework's set.
pub struct Icon {
    /// The name an author writes in a descriptor.
    pub name: &'static str,
    /// Which group it belongs to in the documented index.
    pub group: &'static str,
    /// The drawing instructions, without an `svg` wrapper or any
    /// presentation attributes: the render site owns those.
    pub body: &'static str,
    /// Whether filling it reads as a state rather than a blob.
    pub fillable: bool,
    /// Whether its direction carries meaning and flips under RTL.
    pub mirror: bool,
}

/// Every icon the framework ships, sorted by name. 197 of them.
pub static ICONS: [Icon; 197] = [
    Icon {
        name: "activity",
        group: "objects",
        body: r##"<path d="M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "alarm-clock",
        group: "time-place",
        body: r##"<circle cx="12" cy="13" r="8" /> <path d="M12 9v4l2 2" /> <path d="M5 3 2 6" /> <path d="m22 6-3-3" /> <path d="M6.38 18.7 4 21" /> <path d="M17.64 18.67 20 21" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "arrow-up-down",
        group: "chrome",
        body: r##"<path d="m21 16-4 4-4-4" /> <path d="M17 20V4" /> <path d="m3 8 4-4 4 4" /> <path d="M7 4v16" />"##,
        fillable: false,
        mirror: true,
    },
    Icon {
        name: "at-sign",
        group: "communication",
        body: r##"<circle cx="12" cy="12" r="4" /> <path d="M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-4 8" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "award",
        group: "objects",
        body: r##"<path d="m15.477 12.89 1.515 8.526a.5.5 0 0 1-.81.47l-3.58-2.687a1 1 0 0 0-1.197 0l-3.586 2.686a.5.5 0 0 1-.81-.469l1.514-8.526" /> <circle cx="12" cy="8" r="6" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "badge-percent",
        group: "commerce",
        body: r##"<path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z" /> <path d="m15 9-6 6" /> <path d="M9 9h.01" /> <path d="M15 15h.01" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "banknote",
        group: "commerce",
        body: r##"<rect width="20" height="12" x="2" y="6" rx="2" /> <circle cx="12" cy="12" r="2" /> <path d="M6 12h.01M18 12h.01" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "bell",
        group: "communication",
        body: r##"<path d="M10.268 21a2 2 0 0 0 3.464 0" /> <path d="M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326" />"##,
        fillable: true,
        mirror: false,
    },
    Icon {
        name: "bell-off",
        group: "communication",
        body: r##"<path d="M10.268 21a2 2 0 0 0 3.464 0" /> <path d="M17 17H4a1 1 0 0 1-.74-1.673C4.59 13.956 6 12.499 6 8a6 6 0 0 1 .258-1.742" /> <path d="m2 2 20 20" /> <path d="M8.668 3.01A6 6 0 0 1 18 8c0 2.687.77 4.653 1.707 6.05" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "bell-ring",
        group: "communication",
        body: r##"<path d="M10.268 21a2 2 0 0 0 3.464 0" /> <path d="M22 8c0-2.3-.8-4.3-2-6" /> <path d="M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326" /> <path d="M4 2C2.8 3.7 2 5.7 2 8" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "blocks",
        group: "objects",
        body: r##"<path d="M10 22V7a1 1 0 0 0-1-1H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-5a1 1 0 0 0-1-1H2" /> <rect x="14" y="2" width="8" height="8" rx="1" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "bluetooth",
        group: "technical",
        body: r##"<path d="m7 7 10 10-5 5V2l5 5L7 17" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "bold",
        group: "content",
        body: r##"<path d="M6 12h9a4 4 0 0 1 0 8H7a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h7a4 4 0 0 1 0 8" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "book-open",
        group: "content",
        body: r##"<path d="M12 5v16" /> <path d="M20.001 19A2 2 0 0022 17V5a2 2 0 00-1.999-2L16 3.002A5 5 0 0012 5a5 5 0 00-4-2H4a2 2 0 00-2 2v12a2 2 0 001.999 2H8a5 5 0 014 2 5 5 0 014-2z" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "bookmark",
        group: "content",
        body: r##"<path d="M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z" />"##,
        fillable: true,
        mirror: false,
    },
    Icon {
        name: "bot",
        group: "technical",
        body: r##"<path d="M12 8V4H8" /> <rect width="16" height="12" x="4" y="8" rx="2" /> <path d="M2 14h2" /> <path d="M20 14h2" /> <path d="M15 13v2" /> <path d="M9 13v2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "box",
        group: "objects",
        body: r##"<path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" /> <path d="m3.3 7 8.7 5 8.7-5" /> <path d="M12 22V12" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "boxes",
        group: "objects",
        body: r##"<path d="M2.97 12.92A2 2 0 0 0 2 14.63v3.24a2 2 0 0 0 .97 1.71l3 1.8a2 2 0 0 0 2.06 0L12 19v-5.5l-5-3-4.03 2.42Z" /> <path d="m7 16.5-4.74-2.85" /> <path d="m7 16.5 5-3" /> <path d="M7 16.5v5.17" /> <path d="M12 13.5V19l3.97 2.38a2 2 0 0 0 2.06 0l3-1.8a2 2 0 0 0 .97-1.71v-3.24a2 2 0 0 0-.97-1.71L17 10.5l-5 3Z" /> <path d="m17 16.5-5-3" /> <path d="m17 16.5 4.74-2.85" /> <path d="M17 16.5v5.17" /> <path d="M7.97 4.42A2 2 0 0 0 7 6.13v4.37l5 3 5-3V6.13a2 2 0 0 0-.97-1.71l-3-1.8a2 2 0 0 0-2.06 0l-3 1.8Z" /> <path d="M12 8 7.26 5.15" /> <path d="m12 8 4.74-2.85" /> <path d="M12 13.5V8" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "braces",
        group: "content",
        body: r##"<path d="M8 3H7a2 2 0 0 0-2 2v5a2 2 0 0 1-2 2 2 2 0 0 1 2 2v5c0 1.1.9 2 2 2h1" /> <path d="M16 21h1a2 2 0 0 0 2-2v-5c0-1.1.9-2 2-2a2 2 0 0 1-2-2V5a2 2 0 0 0-2-2h-1" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "briefcase",
        group: "commerce",
        body: r##"<path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" /> <rect width="20" height="14" x="2" y="6" rx="2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "brush",
        group: "objects",
        body: r##"<path d="m11 10 3 3" /> <path d="M6.5 21A3.5 3.5 0 1 0 3 17.5a2.62 2.62 0 0 1-.708 1.792A1 1 0 0 0 3 21z" /> <path d="M9.969 17.031 21.378 5.624a1 1 0 0 0-3.002-3.002L6.967 14.031" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "bug",
        group: "technical",
        body: r##"<path d="M12 20v-9" /> <path d="M14 7a4 4 0 0 1 4 4v3a6 6 0 0 1-12 0v-3a4 4 0 0 1 4-4z" /> <path d="M14.12 3.88 16 2" /> <path d="M21 21a4 4 0 0 0-3.81-4" /> <path d="M21 5a4 4 0 0 1-3.55 3.97" /> <path d="M22 13h-4" /> <path d="M3 21a4 4 0 0 1 3.81-4" /> <path d="M3 5a4 4 0 0 0 3.55 3.97" /> <path d="M6 13H2" /> <path d="m8 2 1.88 1.88" /> <path d="M9 7.13V6a3 3 0 1 1 6 0v1.13" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "building",
        group: "commerce",
        body: r##"<path d="M12 10h.01" /> <path d="M12 14h.01" /> <path d="M12 6h.01" /> <path d="M16 10h.01" /> <path d="M16 14h.01" /> <path d="M16 6h.01" /> <path d="M8 10h.01" /> <path d="M8 14h.01" /> <path d="M8 6h.01" /> <path d="M9 22v-3a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v3" /> <rect x="4" y="2" width="16" height="20" rx="2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "building-2",
        group: "commerce",
        body: r##"<path d="M10 12h4" /> <path d="M10 8h4" /> <path d="M14 21v-3a2 2 0 0 0-4 0v3" /> <path d="M6 10H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-2" /> <path d="M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "calculator",
        group: "commerce",
        body: r##"<rect width="16" height="20" x="4" y="2" rx="2" /> <line x1="8" x2="16" y1="6" y2="6" /> <line x1="16" x2="16" y1="14" y2="18" /> <path d="M16 10h.01" /> <path d="M12 10h.01" /> <path d="M8 10h.01" /> <path d="M12 14h.01" /> <path d="M8 14h.01" /> <path d="M12 18h.01" /> <path d="M8 18h.01" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "calendar",
        group: "time-place",
        body: r##"<path d="M8 2v3" /> <path d="M16 2v3" /> <rect x="3" y="3" width="18" height="18" rx="2" /> <path d="M3 9h18" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "calendar-days",
        group: "time-place",
        body: r##"<path d="M8 2v3" /> <path d="M16 2v3" /> <rect x="3" y="3" width="18" height="18" rx="2" /> <path d="M3 9h18" /> <path d="M8 13h.01" /> <path d="M12 13h.01" /> <path d="M16 13h.01" /> <path d="M8 17h.01" /> <path d="M12 17h.01" /> <path d="M16 17h.01" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "camera",
        group: "technical",
        body: r##"<path d="M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z" /> <circle cx="12" cy="13" r="3" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "chart-bar",
        group: "commerce",
        body: r##"<path d="M3 3v16a2 2 0 0 0 2 2h16" /> <path d="M7 16h8" /> <path d="M7 11h12" /> <path d="M7 6h3" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "chart-line",
        group: "commerce",
        body: r##"<path d="M3 3v16a2 2 0 0 0 2 2h16" /> <path d="m19 9-5 5-4-4-3 3" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "chart-pie",
        group: "commerce",
        body: r##"<path d="M21 12c.552 0 1.005-.449.95-.998a10 10 0 0 0-8.953-8.951c-.55-.055-.998.398-.998.95v8a1 1 0 0 0 1 1z" /> <path d="M21.21 15.89A10 10 0 1 1 8 2.83" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "check",
        group: "chrome",
        body: r##"<path d="M20 6 9 17l-5-5" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "check-check",
        group: "objects",
        body: r##"<path d="M18 6 7 17l-5-5" /> <path d="m22 10-7.5 7.5L13 16" />"##,
        fillable: true,
        mirror: false,
    },
    Icon {
        name: "chevron-down",
        group: "chrome",
        body: r##"<path d="m6 9 6 6 6-6" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "chevron-left",
        group: "chrome",
        body: r##"<path d="m15 18-6-6 6-6" />"##,
        fillable: false,
        mirror: true,
    },
    Icon {
        name: "chevron-right",
        group: "chrome",
        body: r##"<path d="m9 18 6-6-6-6" />"##,
        fillable: false,
        mirror: true,
    },
    Icon {
        name: "chevron-up",
        group: "chrome",
        body: r##"<path d="m18 15-6-6-6 6" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "chevrons-left",
        group: "chrome",
        body: r##"<path d="m11 17-5-5 5-5" /> <path d="m18 17-5-5 5-5" />"##,
        fillable: false,
        mirror: true,
    },
    Icon {
        name: "chevrons-right",
        group: "chrome",
        body: r##"<path d="m6 17 5-5-5-5" /> <path d="m13 17 5-5-5-5" />"##,
        fillable: false,
        mirror: true,
    },
    Icon {
        name: "circle",
        group: "objects",
        body: r##"<circle cx="12" cy="12" r="10" />"##,
        fillable: true,
        mirror: false,
    },
    Icon {
        name: "circle-alert",
        group: "chrome",
        body: r##"<circle cx="12" cy="12" r="10" /> <line x1="12" x2="12" y1="8" y2="12" /> <line x1="12" x2="12.01" y1="16" y2="16" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "circle-check",
        group: "chrome",
        body: r##"<circle cx="12" cy="12" r="10" /> <path d="m16 9-5.5 5.5L8 12" />"##,
        fillable: true,
        mirror: false,
    },
    Icon {
        name: "circle-help",
        group: "chrome",
        body: r##"<circle cx="12" cy="12" r="10" /> <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" /> <path d="M12 17h.01" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "circle-x",
        group: "chrome",
        body: r##"<circle cx="12" cy="12" r="10" /> <path d="m15 9-6 6" /> <path d="m9 9 6 6" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "clock",
        group: "time-place",
        body: r##"<circle cx="12" cy="12" r="10" /> <path d="M12 6v6l4 2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "cloud",
        group: "technical",
        body: r##"<path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "cloud-download",
        group: "technical",
        body: r##"<path d="M12 13v8l-4-4" /> <path d="m12 21 4-4" /> <path d="M4.393 15.269A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.436 8.284" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "cloud-upload",
        group: "technical",
        body: r##"<path d="M12 13v8" /> <path d="M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242" /> <path d="m8 17 4-4 4 4" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "code",
        group: "content",
        body: r##"<path d="m16 18 6-6-6-6" /> <path d="m8 6-6 6 6 6" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "coins",
        group: "commerce",
        body: r##"<path d="M13.744 17.736a6 6 0 1 1-7.48-7.48" /> <path d="M15 6h1v4" /> <path d="m6.134 14.768.866-.5 2 3.464" /> <circle cx="16" cy="8" r="6" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "columns-3",
        group: "chrome",
        body: r##"<rect width="18" height="18" x="3" y="3" rx="2" /> <path d="M9 3v18" /> <path d="M15 3v18" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "compass",
        group: "time-place",
        body: r##"<circle cx="12" cy="12" r="10" /> <path d="m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "component",
        group: "objects",
        body: r##"<path d="M15.536 11.293a1 1 0 0 0 0 1.414l2.376 2.377a1 1 0 0 0 1.414 0l2.377-2.377a1 1 0 0 0 0-1.414l-2.377-2.377a1 1 0 0 0-1.414 0z" /> <path d="M2.297 11.293a1 1 0 0 0 0 1.414l2.377 2.377a1 1 0 0 0 1.414 0l2.377-2.377a1 1 0 0 0 0-1.414L6.088 8.916a1 1 0 0 0-1.414 0z" /> <path d="M8.916 17.912a1 1 0 0 0 0 1.415l2.377 2.376a1 1 0 0 0 1.414 0l2.377-2.376a1 1 0 0 0 0-1.415l-2.377-2.376a1 1 0 0 0-1.414 0z" /> <path d="M8.916 4.674a1 1 0 0 0 0 1.414l2.377 2.376a1 1 0 0 0 1.414 0l2.377-2.376a1 1 0 0 0 0-1.414l-2.377-2.377a1 1 0 0 0-1.414 0z" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "contact",
        group: "people",
        body: r##"<path d="M16 2v2" /> <path d="M7 21v-2a2 2 0 012-2h6a2 2 0 012 2v2" /> <path d="M8 2v2" /> <circle cx="12" cy="10" r="3" /> <rect x="3" y="3" width="18" height="18" rx="2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "copy",
        group: "chrome",
        body: r##"<rect width="14" height="14" x="8" y="8" rx="2" ry="2" /> <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "cpu",
        group: "technical",
        body: r##"<path d="M12 20v2" /> <path d="M12 2v2" /> <path d="M17 20v2" /> <path d="M17 2v2" /> <path d="M2 12h2" /> <path d="M2 17h2" /> <path d="M2 7h2" /> <path d="M20 12h2" /> <path d="M20 17h2" /> <path d="M20 7h2" /> <path d="M7 20v2" /> <path d="M7 2v2" /> <rect x="4" y="4" width="16" height="16" rx="2" /> <rect x="8" y="8" width="8" height="8" rx="1" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "credit-card",
        group: "commerce",
        body: r##"<rect width="20" height="14" x="2" y="5" rx="2" /> <line x1="2" x2="22" y1="10" y2="10" /> <path d="M6 14h2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "crown",
        group: "objects",
        body: r##"<path d="M11.562 3.266a.5.5 0 0 1 .876 0L15.39 8.87a1 1 0 0 0 1.516.294L21.183 5.5a.5.5 0 0 1 .798.519l-2.834 10.246a1 1 0 0 1-.956.734H5.81a1 1 0 0 1-.957-.734L2.02 6.02a.5.5 0 0 1 .798-.519l4.276 3.664a1 1 0 0 0 1.516-.294z" /> <path d="M5 21h14" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "database",
        group: "technical",
        body: r##"<ellipse cx="12" cy="5" rx="9" ry="3" /> <path d="M3 5V19A9 3 0 0 0 21 19V5" /> <path d="M3 12A9 3 0 0 0 21 12" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "download",
        group: "chrome",
        body: r##"<path d="M12 15V3" /> <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /> <path d="m7 10 5 5 5-5" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "droplet",
        group: "objects",
        body: r##"<path d="M12 22a7 7 0 0 0 7-7c0-2-1-3.9-3-5.5s-3.5-4-4-6.5c-.5 2.5-2 4.9-4 6.5C6 11.1 5 13 5 15a7 7 0 0 0 7 7z" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "ellipsis",
        group: "chrome",
        body: r##"<circle cx="12" cy="12" r="1" /> <circle cx="19" cy="12" r="1" /> <circle cx="5" cy="12" r="1" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "ellipsis-vertical",
        group: "chrome",
        body: r##"<circle cx="12" cy="12" r="1" /> <circle cx="12" cy="5" r="1" /> <circle cx="12" cy="19" r="1" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "external-link",
        group: "chrome",
        body: r##"<path d="M15 3h6v6" /> <path d="M10 14 21 3" /> <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />"##,
        fillable: false,
        mirror: true,
    },
    Icon {
        name: "eye",
        group: "chrome",
        body: r##"<path d="M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0" /> <circle cx="12" cy="12" r="3" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "eye-off",
        group: "chrome",
        body: r##"<path d="M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49" /> <path d="M14.084 14.158a3 3 0 0 1-4.242-4.242" /> <path d="M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143" /> <path d="m2 2 20 20" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "file",
        group: "content",
        body: r##"<path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z" /> <path d="M14 2v5a1 1 0 0 0 1 1h5" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "file-text",
        group: "content",
        body: r##"<path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z" /> <path d="M14 2v5a1 1 0 0 0 1 1h5" /> <path d="M10 9H8" /> <path d="M16 13H8" /> <path d="M16 17H8" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "files",
        group: "content",
        body: r##"<path d="M15 2h-4a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V8" /> <path d="M16.706 2.706A2.4 2.4 0 0 0 15 2v5a1 1 0 0 0 1 1h5a2.4 2.4 0 0 0-.706-1.706z" /> <path d="M5 7a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h8a2 2 0 0 0 1.732-1" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "film",
        group: "content",
        body: r##"<rect width="18" height="18" x="3" y="3" rx="2" /> <path d="M7 3v18" /> <path d="M3 7.5h4" /> <path d="M3 12h18" /> <path d="M3 16.5h4" /> <path d="M17 3v18" /> <path d="M17 7.5h4" /> <path d="M17 16.5h4" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "fingerprint",
        group: "people",
        body: r##"<path d="M12 10a2 2 0 0 0-2 2c0 1.02-.1 2.51-.26 4" /> <path d="M14 13.12c0 2.38 0 6.38-1 8.88" /> <path d="M17.29 21.02c.12-.6.43-2.3.5-3.02" /> <path d="M2 12a10 10 0 0 1 18-6" /> <path d="M2 16h.01" /> <path d="M21.8 16c.2-2 .131-5.354 0-6" /> <path d="M5 19.5C5.5 18 6 15 6 12a6 6 0 0 1 .34-2" /> <path d="M8.65 22c.21-.66.45-1.32.57-2" /> <path d="M9 6.8a6 6 0 0 1 9 5.2v2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "flag",
        group: "content",
        body: r##"<path d="M4 22V4a1 1 0 0 1 .4-.8A6 6 0 0 1 8 2c3 0 5 2 7.333 2q2 0 3.067-.8A1 1 0 0 1 20 4v10a1 1 0 0 1-.4.8A6 6 0 0 1 16 16c-3 0-5-2-8-2a6 6 0 0 0-4 1.528" />"##,
        fillable: true,
        mirror: false,
    },
    Icon {
        name: "flame",
        group: "objects",
        body: r##"<path d="M12 3q1 4 4 6.5t3 5.5a1 1 0 0 1-14 0 5 5 0 0 1 1-3 1 1 0 0 0 5 0c0-2-1.5-3-1.5-5q0-2 2.5-4" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "folder",
        group: "content",
        body: r##"<path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "folder-open",
        group: "content",
        body: r##"<path d="m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "folder-plus",
        group: "content",
        body: r##"<path d="M12 10v6" /> <path d="M9 13h6" /> <path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "funnel",
        group: "chrome",
        body: r##"<path d="M10 20a1 1 0 0 0 .553.895l2 1A1 1 0 0 0 14 21v-7a2 2 0 0 1 .517-1.341L21.74 4.67A1 1 0 0 0 21 3H3a1 1 0 0 0-.742 1.67l7.225 7.989A2 2 0 0 1 10 14z" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "gauge",
        group: "objects",
        body: r##"<path d="m12 14 4-4" /> <path d="M3.34 19a10 10 0 1 1 17.32 0" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "gift",
        group: "commerce",
        body: r##"<path d="M12 7v14" /> <path d="M20 11v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-8" /> <path d="M7.5 7a1 1 0 0 1 0-5A4.8 8 0 0 1 12 7a4.8 8 0 0 1 4.5-5 1 1 0 0 1 0 5" /> <rect x="3" y="7" width="18" height="4" rx="1" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "git-branch",
        group: "technical",
        body: r##"<path d="M15 6a9 9 0 0 0-9 9V3" /> <circle cx="18" cy="6" r="3" /> <circle cx="6" cy="18" r="3" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "globe",
        group: "time-place",
        body: r##"<circle cx="12" cy="12" r="10" /> <path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20" /> <path d="M2 12h20" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "grip-vertical",
        group: "chrome",
        body: r##"<circle cx="9" cy="12" r="1" /> <circle cx="9" cy="5" r="1" /> <circle cx="9" cy="19" r="1" /> <circle cx="15" cy="12" r="1" /> <circle cx="15" cy="5" r="1" /> <circle cx="15" cy="19" r="1" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "hammer",
        group: "objects",
        body: r##"<path d="m15 12-9.373 9.373a1 1 0 0 1-3.001-3L12 9" /> <path d="m18 15 4-4" /> <path d="m21.5 11.5-1.914-1.914A2 2 0 0 1 19 8.172v-.344a2 2 0 0 0-.586-1.414l-1.657-1.657A6 6 0 0 0 12.516 3H9l1.243 1.243A6 6 0 0 1 12 8.485V10l2 2h1.172a2 2 0 0 1 1.414.586L18.5 14.5" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "hard-drive",
        group: "technical",
        body: r##"<path d="M10 16h.01" /> <path d="M2.212 11.577a2 2 0 0 0-.212.896V18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-5.527a2 2 0 0 0-.212-.896L18.55 5.11A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z" /> <path d="M21.946 12.013H2.054" /> <path d="M6 16h.01" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "heading",
        group: "content",
        body: r##"<path d="M6 12h12" /> <path d="M6 20V4" /> <path d="M18 20V4" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "heart",
        group: "content",
        body: r##"<path d="M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5" />"##,
        fillable: true,
        mirror: false,
    },
    Icon {
        name: "history",
        group: "chrome",
        body: r##"<path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" /> <path d="M3 3v5h5" /> <path d="M12 7v5l4 2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "home",
        group: "time-place",
        body: r##"<path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8" /> <path d="M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "id-card",
        group: "people",
        body: r##"<path d="M13 19a4 4 0 00-8 0" /> <path d="M16 10h2" /> <path d="M16 14h2" /> <circle cx="9" cy="12" r="3" /> <rect x="2" y="5" width="20" height="14" rx="2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "image",
        group: "content",
        body: r##"<rect width="18" height="18" x="3" y="3" rx="2" ry="2" /> <circle cx="9" cy="9" r="2" /> <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "images",
        group: "content",
        body: r##"<path d="m22 11-1.296-1.296a2.4 2.4 0 0 0-3.408 0L11 16" /> <path d="M4 8a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2" /> <circle cx="13" cy="7" r="1" fill="currentColor" /> <rect x="8" y="2" width="14" height="14" rx="2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "info",
        group: "chrome",
        body: r##"<circle cx="12" cy="12" r="10" /> <path d="M12 16v-4" /> <path d="M12 8h.01" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "italic",
        group: "content",
        body: r##"<line x1="19" x2="10" y1="4" y2="4" /> <line x1="14" x2="5" y1="20" y2="20" /> <line x1="15" x2="9" y1="4" y2="20" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "key",
        group: "people",
        body: r##"<path d="m2 21 9.6-9.6" /> <path d="m7.5 15.5 2.3 2.3a1 1 0 0 1 0 1.4l-2.1 2.1a1 1 0 0 1-1.4 0L4 19" /> <circle cx="15.5" cy="7.5" r="5.5" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "landmark",
        group: "commerce",
        body: r##"<path d="M10 18v-7" /> <path d="M11.119 2.205a2 2 0 0 1 1.762 0l7.84 3.846A.5.5 0 0 1 20.5 7h-17a.5.5 0 0 1-.22-.949z" /> <path d="M14 18v-7" /> <path d="M18 18v-7" /> <path d="M3 22h18" /> <path d="M6 18v-7" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "laptop",
        group: "technical",
        body: r##"<path d="M18 5a2 2 0 0 1 2 2v8.526a2 2 0 0 0 .212.897l1.068 2.127a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45l1.068-2.127A2 2 0 0 0 4 15.526V7a2 2 0 0 1 2-2z" /> <path d="M20.054 15.987H3.946" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "layers",
        group: "objects",
        body: r##"<path d="M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83z" /> <path d="M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12" /> <path d="M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "layout-dashboard",
        group: "chrome",
        body: r##"<rect width="7" height="9" x="3" y="3" rx="1" /> <rect width="7" height="5" x="14" y="3" rx="1" /> <rect width="7" height="9" x="14" y="12" rx="1" /> <rect width="7" height="5" x="3" y="16" rx="1" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "layout-grid",
        group: "chrome",
        body: r##"<rect width="7" height="7" x="3" y="3" rx="1" /> <rect width="7" height="7" x="14" y="3" rx="1" /> <rect width="7" height="7" x="14" y="14" rx="1" /> <rect width="7" height="7" x="3" y="14" rx="1" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "layout-template",
        group: "objects",
        body: r##"<rect width="18" height="7" x="3" y="3" rx="1" /> <rect width="9" height="7" x="3" y="14" rx="1" /> <rect width="5" height="7" x="16" y="14" rx="1" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "leaf",
        group: "objects",
        body: r##"<path d="M11 20a10 10 0 0010-10 25.9 25.9 0 00-1.04-7.281 1 1 0 00-1.755-.325C15.833 5.5 13 5.5 9.8 6.1A7 7 0 0011 20" /> <path d="M2 21a5 5 0 012.911-4.544C7.613 15.212 8.351 15.24 11 13" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "lightbulb",
        group: "objects",
        body: r##"<path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5" /> <path d="M9 18h6" /> <path d="M10 22h4" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "link",
        group: "content",
        body: r##"<path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" /> <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "list",
        group: "chrome",
        body: r##"<path d="M3 5h.01" /> <path d="M3 12h.01" /> <path d="M3 19h.01" /> <path d="M8 5h13" /> <path d="M8 12h13" /> <path d="M8 19h13" />"##,
        fillable: false,
        mirror: true,
    },
    Icon {
        name: "list-ordered",
        group: "content",
        body: r##"<path d="M11 5h10" /> <path d="M11 12h10" /> <path d="M11 19h10" /> <path d="M4 4h1v5" /> <path d="M4 9h2" /> <path d="M6.5 20H3.4c0-1 2.6-1.925 2.6-3.5a1.5 1.5 0 0 0-2.6-1.02" />"##,
        fillable: false,
        mirror: true,
    },
    Icon {
        name: "loader-circle",
        group: "chrome",
        body: r##"<path d="M21 12a9 9 0 1 1-6.219-8.56" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "lock",
        group: "people",
        body: r##"<rect width="18" height="11" x="3" y="11" rx="2" ry="2" /> <path d="M7 11V7a5 5 0 0 1 10 0v4" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "lock-open",
        group: "people",
        body: r##"<rect width="18" height="11" x="3" y="11" rx="2" ry="2" /> <path d="M7 11V7a5 5 0 0 1 9.9-1" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "log-in",
        group: "chrome",
        body: r##"<path d="m10 17 5-5-5-5" /> <path d="M15 12H3" /> <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />"##,
        fillable: false,
        mirror: true,
    },
    Icon {
        name: "log-out",
        group: "chrome",
        body: r##"<path d="m16 17 5-5-5-5" /> <path d="M21 12H9" /> <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />"##,
        fillable: false,
        mirror: true,
    },
    Icon {
        name: "mail",
        group: "communication",
        body: r##"<path d="m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7" /> <rect x="2" y="4" width="20" height="16" rx="2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "map",
        group: "time-place",
        body: r##"<path d="M14.106 5.553a2 2 0 0 0 1.788 0l3.659-1.83A1 1 0 0 1 21 4.619v12.764a1 1 0 0 1-.553.894l-4.553 2.277a2 2 0 0 1-1.788 0l-4.212-2.106a2 2 0 0 0-1.788 0l-3.659 1.83A1 1 0 0 1 3 19.381V6.618a1 1 0 0 1 .553-.894l4.553-2.277a2 2 0 0 1 1.788 0z" /> <path d="M15 5.764v15" /> <path d="M9 3.236v15" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "map-pin",
        group: "time-place",
        body: r##"<path d="M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0" /> <circle cx="12" cy="10" r="3" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "map-pinned",
        group: "time-place",
        body: r##"<path d="M18 8c0 3.613-3.869 7.429-5.393 8.795a1 1 0 0 1-1.214 0C9.87 15.429 6 11.613 6 8a6 6 0 0 1 12 0" /> <circle cx="12" cy="8" r="2" /> <path d="M8.714 14h-3.71a1 1 0 0 0-.948.683l-2.004 6A1 1 0 0 0 3 22h18a1 1 0 0 0 .948-1.316l-2-6a1 1 0 0 0-.949-.684h-3.712" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "megaphone",
        group: "communication",
        body: r##"<path d="M11 6a13 13 0 0 0 8.4-2.8A1 1 0 0 1 21 4v12a1 1 0 0 1-1.6.8A13 13 0 0 0 11 14H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2z" /> <path d="M6 14a12 12 0 0 0 2.4 7.2 2 2 0 0 0 3.2-2.4A8 8 0 0 1 10 14" /> <path d="M8 6v8" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "menu",
        group: "chrome",
        body: r##"<path d="M4 5h16" /> <path d="M4 12h16" /> <path d="M4 19h16" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "message-circle",
        group: "communication",
        body: r##"<path d="M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "message-square",
        group: "communication",
        body: r##"<path d="M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "mic",
        group: "technical",
        body: r##"<path d="M12 19v3" /> <path d="M19 10v2a7 7 0 0 1-14 0v-2" /> <rect x="9" y="2" width="6" height="13" rx="3" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "monitor",
        group: "chrome",
        body: r##"<rect width="20" height="14" x="2" y="3" rx="2" /> <line x1="8" x2="16" y1="21" y2="21" /> <line x1="12" x2="12" y1="17" y2="21" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "moon",
        group: "chrome",
        body: r##"<path d="M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "music",
        group: "content",
        body: r##"<path d="M9 18V5l12-2v13" /> <circle cx="6" cy="18" r="3" /> <circle cx="18" cy="16" r="3" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "navigation",
        group: "time-place",
        body: r##"<polygon points="3 11 22 2 13 21 11 13 3 11" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "newspaper",
        group: "content",
        body: r##"<path d="M15 18h-5" /> <path d="M18 14h-8" /> <path d="M4 22h16a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2v16a2 2 0 0 1-4 0v-9a2 2 0 0 1 2-2h2" /> <rect width="8" height="4" x="10" y="6" rx="1" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "notebook-pen",
        group: "content",
        body: r##"<path d="M13.4 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-7.4" /> <path d="M2 6h4" /> <path d="M2 10h4" /> <path d="M2 14h4" /> <path d="M2 18h4" /> <path d="M21.378 5.626a1 1 0 1 0-3.004-3.004l-5.01 5.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "notepad-text",
        group: "content",
        body: r##"<path d="M8 2v4" /> <path d="M12 2v4" /> <path d="M16 2v4" /> <rect width="16" height="18" x="4" y="4" rx="2" /> <path d="M8 10h6" /> <path d="M8 14h8" /> <path d="M8 18h5" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "package",
        group: "commerce",
        body: r##"<path d="M11 21.73a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73z" /> <path d="M12 22V12" /> <polyline points="3.29 7 12 12 20.71 7" /> <path d="m7.5 4.27 9 5.15" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "paintbrush",
        group: "objects",
        body: r##"<path d="m14.622 17.897-10.68-2.913" /> <path d="M18.376 2.622a1 1 0 1 1 3.002 3.002L17.36 9.643a.5.5 0 0 0 0 .707l.944.944a2.41 2.41 0 0 1 0 3.408l-.944.944a.5.5 0 0 1-.707 0L8.354 7.348a.5.5 0 0 1 0-.707l.944-.944a2.41 2.41 0 0 1 3.408 0l.944.944a.5.5 0 0 0 .707 0z" /> <path d="M9 8c-1.804 2.71-3.97 3.46-6.583 3.948a.507.507 0 0 0-.302.819l7.32 8.883a1 1 0 0 0 1.185.204C12.735 20.405 16 16.792 16 15" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "palette",
        group: "objects",
        body: r##"<path d="M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z" /> <circle cx="13.5" cy="6.5" r=".5" fill="currentColor" /> <circle cx="17.5" cy="10.5" r=".5" fill="currentColor" /> <circle cx="6.5" cy="12.5" r=".5" fill="currentColor" /> <circle cx="8.5" cy="7.5" r=".5" fill="currentColor" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "panel-left",
        group: "chrome",
        body: r##"<rect width="18" height="18" x="3" y="3" rx="2" /> <path d="M9 3v18" />"##,
        fillable: false,
        mirror: true,
    },
    Icon {
        name: "paperclip",
        group: "content",
        body: r##"<path d="m16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "pencil",
        group: "chrome",
        body: r##"<path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z" /> <path d="m15 5 4 4" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "percent",
        group: "commerce",
        body: r##"<line x1="19" x2="5" y1="5" y2="19" /> <circle cx="6.5" cy="6.5" r="2.5" /> <circle cx="17.5" cy="17.5" r="2.5" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "phone",
        group: "communication",
        body: r##"<path d="M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "pin",
        group: "content",
        body: r##"<path d="M12 17v5" /> <path d="M9 10.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H8a2 2 0 0 0 0 4 1 1 0 0 1 1 1z" />"##,
        fillable: true,
        mirror: false,
    },
    Icon {
        name: "plug",
        group: "technical",
        body: r##"<path d="M12 22v-5" /> <path d="M15 8V2" /> <path d="M17 8a1 1 0 0 1 1 1v4a4 4 0 0 1-4 4h-4a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1z" /> <path d="M9 8V2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "plus",
        group: "chrome",
        body: r##"<path d="M5 12h14" /> <path d="M12 5v14" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "printer",
        group: "technical",
        body: r##"<path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" /> <path d="M6 9V3a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v6" /> <rect x="6" y="14" width="12" height="8" rx="1" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "puzzle",
        group: "objects",
        body: r##"<path d="M15.39 4.39a1 1 0 0 0 1.68-.474 2.5 2.5 0 1 1 3.014 3.015 1 1 0 0 0-.474 1.68l1.683 1.682a2.414 2.414 0 0 1 0 3.414L19.61 15.39a1 1 0 0 1-1.68-.474 2.5 2.5 0 1 0-3.014 3.015 1 1 0 0 1 .474 1.68l-1.683 1.682a2.414 2.414 0 0 1-3.414 0L8.61 19.61a1 1 0 0 0-1.68.474 2.5 2.5 0 1 1-3.014-3.015 1 1 0 0 0 .474-1.68l-1.683-1.682a2.414 2.414 0 0 1 0-3.414L4.39 8.61a1 1 0 0 1 1.68.474 2.5 2.5 0 1 0 3.014-3.015 1 1 0 0 1-.474-1.68l1.683-1.682a2.414 2.414 0 0 1 3.414 0z" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "qr-code",
        group: "technical",
        body: r##"<rect width="5" height="5" x="3" y="3" rx="1" /> <rect width="5" height="5" x="16" y="3" rx="1" /> <rect width="5" height="5" x="3" y="16" rx="1" /> <path d="M21 16h-3a2 2 0 0 0-2 2v3" /> <path d="M21 21v.01" /> <path d="M12 7v3a2 2 0 0 1-2 2H7" /> <path d="M3 12h.01" /> <path d="M12 3h.01" /> <path d="M12 16v.01" /> <path d="M16 12h1" /> <path d="M21 12v.01" /> <path d="M12 21v-1" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "quote",
        group: "content",
        body: r##"<path d="M16 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2 1 1 0 0 1 1 1v1a2 2 0 0 1-2 2 1 1 0 0 0-1 1v2a1 1 0 0 0 1 1 6 6 0 0 0 6-6V5a2 2 0 0 0-2-2z" /> <path d="M5 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2 1 1 0 0 1 1 1v1a2 2 0 0 1-2 2 1 1 0 0 0-1 1v2a1 1 0 0 0 1 1 6 6 0 0 0 6-6V5a2 2 0 0 0-2-2z" />"##,
        fillable: false,
        mirror: true,
    },
    Icon {
        name: "receipt",
        group: "commerce",
        body: r##"<path d="M12 17V7" /> <path d="M16 8h-6a2 2 0 0 0 0 4h4a2 2 0 0 1 0 4H8" /> <path d="M4 3a1 1 0 0 1 1-1 1.3 1.3 0 0 1 .7.2l.933.6a1.3 1.3 0 0 0 1.4 0l.934-.6a1.3 1.3 0 0 1 1.4 0l.933.6a1.3 1.3 0 0 0 1.4 0l.933-.6a1.3 1.3 0 0 1 1.4 0l.934.6a1.3 1.3 0 0 0 1.4 0l.933-.6A1.3 1.3 0 0 1 19 2a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1 1.3 1.3 0 0 1-.7-.2l-.933-.6a1.3 1.3 0 0 0-1.4 0l-.934.6a1.3 1.3 0 0 1-1.4 0l-.933-.6a1.3 1.3 0 0 0-1.4 0l-.933.6a1.3 1.3 0 0 1-1.4 0l-.934-.6a1.3 1.3 0 0 0-1.4 0l-.933.6a1.3 1.3 0 0 1-.7.2 1 1 0 0 1-1-1z" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "redo-2",
        group: "chrome",
        body: r##"<path d="m15 14 5-5-5-5" /> <path d="M20 9H9.5A5.5 5.5 0 0 0 4 14.5A5.5 5.5 0 0 0 9.5 20H13" />"##,
        fillable: false,
        mirror: true,
    },
    Icon {
        name: "refresh-cw",
        group: "chrome",
        body: r##"<path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" /> <path d="M21 3v5h-5" /> <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" /> <path d="M8 16H3v5" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "rocket",
        group: "objects",
        body: r##"<path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" /> <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09" /> <path d="M9 12a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.4 22.4 0 0 1-4 2z" /> <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 .05 5 .05" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "rss",
        group: "communication",
        body: r##"<path d="M4 11a9 9 0 0 1 9 9" /> <path d="M4 4a16 16 0 0 1 16 16" /> <circle cx="5" cy="19" r="1" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "save",
        group: "chrome",
        body: r##"<path d="M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z" /> <path d="M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7" /> <path d="M7 3v4a1 1 0 0 0 1 1h7" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "scale",
        group: "commerce",
        body: r##"<path d="M12 3v18" /> <path d="m19 8 3 8a5 5 0 0 1-6 0zV7" /> <path d="M3 7h1a17 17 0 0 0 8-2 17 17 0 0 0 8 2h1" /> <path d="m5 8 3 8a5 5 0 0 1-6 0zV7" /> <path d="M7 21h10" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "search",
        group: "chrome",
        body: r##"<path d="m21 21-4.34-4.34" /> <circle cx="11" cy="11" r="8" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "send",
        group: "communication",
        body: r##"<path d="M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z" /> <path d="m21.854 2.147-10.94 10.939" />"##,
        fillable: false,
        mirror: true,
    },
    Icon {
        name: "server",
        group: "technical",
        body: r##"<rect width="20" height="8" x="2" y="2" rx="2" ry="2" /> <rect width="20" height="8" x="2" y="14" rx="2" ry="2" /> <line x1="6" x2="6.01" y1="6" y2="6" /> <line x1="6" x2="6.01" y1="18" y2="18" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "settings",
        group: "chrome",
        body: r##"<path d="M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915" /> <circle cx="12" cy="12" r="3" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "shield",
        group: "people",
        body: r##"<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "shield-check",
        group: "people",
        body: r##"<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" /> <path d="m9 12 2 2 4-4" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "shopping-bag",
        group: "commerce",
        body: r##"<path d="M16 10a4 4 0 0 1-8 0" /> <path d="M3.103 6.034h17.794" /> <path d="M3.4 5.467a2 2 0 0 0-.4 1.2V20a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.667a2 2 0 0 0-.4-1.2l-2-2.667A2 2 0 0 0 17 2H7a2 2 0 0 0-1.6.8z" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "shopping-cart",
        group: "commerce",
        body: r##"<path d="m2.05 2.05 1.099-.028a1 1 0 0 1 1.008.815l2.69 14.347A1 1 0 0 0 7.83 18H18" /> <path d="M4.563 5h16.435a1 1 0 0 1 .981 1.204l-1.026 6.226A2 2 0 0 1 18.962 14H6.25" /> <circle cx="18" cy="20" r="2" /> <circle cx="8" cy="20" r="2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "sliders-horizontal",
        group: "chrome",
        body: r##"<path d="M10 5H3" /> <path d="M12 19H3" /> <path d="M14 3v4" /> <path d="M16 17v4" /> <path d="M21 12h-9" /> <path d="M21 19h-5" /> <path d="M21 5h-7" /> <path d="M8 10v4" /> <path d="M8 12H3" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "smartphone",
        group: "technical",
        body: r##"<rect width="14" height="20" x="5" y="2" rx="2" ry="2" /> <path d="M12 18h.01" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "sparkles",
        group: "technical",
        body: r##"<path d="M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z" /> <path d="M20 2v4" /> <path d="M22 4h-4" /> <circle cx="4" cy="20" r="2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "square",
        group: "objects",
        body: r##"<rect width="18" height="18" x="3" y="3" rx="2" />"##,
        fillable: true,
        mirror: false,
    },
    Icon {
        name: "square-check",
        group: "objects",
        body: r##"<rect width="18" height="18" x="3" y="3" rx="2" /> <path d="m16 9-5.5 5.5L8 12" />"##,
        fillable: true,
        mirror: false,
    },
    Icon {
        name: "square-pen",
        group: "content",
        body: r##"<path d="M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" /> <path d="M18.375 2.625a1 1 0 0 1 3 3l-9.013 9.014a2 2 0 0 1-.853.505l-2.873.84a.5.5 0 0 1-.62-.62l.84-2.873a2 2 0 0 1 .506-.852z" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "star",
        group: "content",
        body: r##"<path d="M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z" />"##,
        fillable: true,
        mirror: false,
    },
    Icon {
        name: "store",
        group: "commerce",
        body: r##"<path d="M15 21v-5a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v5" /> <path d="M17.774 10.31a1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.451 0 1.12 1.12 0 0 0-1.548 0 2.5 2.5 0 0 1-3.452 0 1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.77-3.248l2.889-4.184A2 2 0 0 1 7 2h10a2 2 0 0 1 1.653.873l2.895 4.192a2.5 2.5 0 0 1-3.774 3.244" /> <path d="M4 10.95V19a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8.05" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "sun",
        group: "chrome",
        body: r##"<circle cx="12" cy="12" r="4" /> <path d="M12 2v2" /> <path d="M12 20v2" /> <path d="m4.93 4.93 1.41 1.41" /> <path d="m17.66 17.66 1.41 1.41" /> <path d="M2 12h2" /> <path d="M20 12h2" /> <path d="m6.34 17.66-1.41 1.41" /> <path d="m19.07 4.93-1.41 1.41" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "tablet",
        group: "technical",
        body: r##"<rect width="16" height="20" x="4" y="2" rx="2" ry="2" /> <line x1="12" x2="12.01" y1="18" y2="18" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "tag",
        group: "content",
        body: r##"<path d="M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z" /> <circle cx="7.5" cy="7.5" r=".5" fill="currentColor" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "tags",
        group: "content",
        body: r##"<path d="M13.172 2a2 2 0 0 1 1.414.586l6.71 6.71a2.4 2.4 0 0 1 0 3.408l-4.592 4.592a2.4 2.4 0 0 1-3.408 0l-6.71-6.71A2 2 0 0 1 6 9.172V3a1 1 0 0 1 1-1z" /> <path d="M2 7v6.172a2 2 0 0 0 .586 1.414l6.71 6.71a2.4 2.4 0 0 0 3.191.193" /> <circle cx="10.5" cy="6.5" r=".5" fill="currentColor" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "target",
        group: "objects",
        body: r##"<circle cx="12" cy="12" r="10" /> <circle cx="12" cy="12" r="6" /> <circle cx="12" cy="12" r="2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "terminal",
        group: "technical",
        body: r##"<path d="M12 19h8" /> <path d="m4 17 6-6-6-6" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "ticket",
        group: "commerce",
        body: r##"<path d="M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z" /> <path d="M13 5v2" /> <path d="M13 17v2" /> <path d="M13 11v2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "timer",
        group: "time-place",
        body: r##"<line x1="10" x2="14" y1="2" y2="2" /> <line x1="12" x2="15" y1="14" y2="11" /> <circle cx="12" cy="14" r="8" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "trash-2",
        group: "chrome",
        body: r##"<path d="M10 11v6" /> <path d="M14 11v6" /> <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6" /> <path d="M3 6h18" /> <path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "trending-down",
        group: "commerce",
        body: r##"<path d="M16 17h6v-6" /> <path d="m22 17-8.5-8.5-5 5L2 7" />"##,
        fillable: false,
        mirror: true,
    },
    Icon {
        name: "trending-up",
        group: "commerce",
        body: r##"<path d="M16 7h6v6" /> <path d="m22 7-8.5 8.5-5-5L2 17" />"##,
        fillable: false,
        mirror: true,
    },
    Icon {
        name: "triangle",
        group: "objects",
        body: r##"<path d="M13.73 4a2 2 0 0 0-3.46 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z" />"##,
        fillable: true,
        mirror: false,
    },
    Icon {
        name: "triangle-alert",
        group: "chrome",
        body: r##"<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3" /> <path d="M12 9v4" /> <path d="M12 17h.01" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "trophy",
        group: "objects",
        body: r##"<path d="M10 14.66V17a1 1 0 0 1-1 1 2 2 0 0 0-2 2v2" /> <path d="M14 14.66V17a1 1 0 0 0 1 1 2 2 0 0 1 2 2v2" /> <path d="M17.916 10H19.5A2.5 2.5 0 0 0 22 7.5V5a1 1 0 0 0-1-1h-3" /> <path d="M4 22h16" /> <path d="M6 9a6 6 0 0 0 12 0V3a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1z" /> <path d="M6.084 10H4.5A2.5 2.5 0 0 1 2 7.5V5a1 1 0 0 1 1-1h3" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "truck",
        group: "commerce",
        body: r##"<path d="M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2" /> <path d="M15 18H9" /> <path d="M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14" /> <circle cx="17" cy="18" r="2" /> <circle cx="7" cy="18" r="2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "type",
        group: "content",
        body: r##"<path d="M12 4v16" /> <path d="M4 7V5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2" /> <path d="M9 20h6" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "underline",
        group: "content",
        body: r##"<path d="M6 4v6a6 6 0 0 0 12 0V4" /> <line x1="4" x2="20" y1="20" y2="20" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "undo-2",
        group: "chrome",
        body: r##"<path d="M9 14 4 9l5-5" /> <path d="M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11" />"##,
        fillable: false,
        mirror: true,
    },
    Icon {
        name: "unlink",
        group: "content",
        body: r##"<path d="m18.84 12.25 1.72-1.71h-.02a5.004 5.004 0 0 0-.12-7.07 5.006 5.006 0 0 0-6.95 0l-1.72 1.71" /> <path d="m5.17 11.75-1.71 1.71a5.004 5.004 0 0 0 .12 7.07 5.006 5.006 0 0 0 6.95 0l1.71-1.71" /> <line x1="8" x2="8" y1="2" y2="5" /> <line x1="2" x2="5" y1="8" y2="8" /> <line x1="16" x2="16" y1="19" y2="22" /> <line x1="19" x2="22" y1="16" y2="16" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "upload",
        group: "chrome",
        body: r##"<path d="M12 3v12" /> <path d="m17 8-5-5-5 5" /> <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "user",
        group: "people",
        body: r##"<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" /> <circle cx="12" cy="7" r="4" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "user-plus",
        group: "people",
        body: r##"<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" /> <circle cx="9" cy="7" r="4" /> <line x1="19" x2="19" y1="8" y2="14" /> <line x1="22" x2="16" y1="11" y2="11" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "user-round",
        group: "people",
        body: r##"<circle cx="12" cy="8" r="5" /> <path d="M20 21a8 8 0 0 0-16 0" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "users",
        group: "people",
        body: r##"<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" /> <path d="M16 3.128a4 4 0 0 1 0 7.744" /> <path d="M22 21v-2a4 4 0 0 0-3-3.87" /> <circle cx="9" cy="7" r="4" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "video",
        group: "technical",
        body: r##"<path d="m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5" /> <rect x="2" y="6" width="14" height="12" rx="2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "wallet",
        group: "commerce",
        body: r##"<path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1" /> <path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "wand-sparkles",
        group: "technical",
        body: r##"<path d="m21.64 3.64-1.28-1.28a1.21 1.21 0 0 0-1.72 0L2.36 18.64a1.21 1.21 0 0 0 0 1.72l1.28 1.28a1.2 1.2 0 0 0 1.72 0L21.64 5.36a1.2 1.2 0 0 0 0-1.72" /> <path d="m14 7 3 3" /> <path d="M5 6v4" /> <path d="M19 14v4" /> <path d="M10 2v2" /> <path d="M7 8H3" /> <path d="M21 16h-4" /> <path d="M11 3H9" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "webhook",
        group: "technical",
        body: r##"<path d="M18 16.98h-5.99c-1.1 0-1.95.94-2.48 1.9A4 4 0 0 1 2 17c.01-.7.2-1.4.57-2" /> <path d="m6 17 3.13-5.78c.53-.97.1-2.18-.5-3.1a4 4 0 1 1 6.89-4.06" /> <path d="m12 6 3.13 5.73C15.66 12.7 16.9 13 18 13a4 4 0 0 1 0 8" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "wifi",
        group: "technical",
        body: r##"<path d="M12 20h.01" /> <path d="M2 8.82a15 15 0 0 1 20 0" /> <path d="M5 12.859a10 10 0 0 1 14 0" /> <path d="M8.5 16.429a5 5 0 0 1 7 0" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "workflow",
        group: "technical",
        body: r##"<rect width="8" height="8" x="3" y="3" rx="2" /> <path d="M7 11v4a2 2 0 0 0 2 2h4" /> <rect width="8" height="8" x="13" y="13" rx="2" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "wrench",
        group: "objects",
        body: r##"<path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-8.259 7.057l-7.91 7.91a1 1 0 0 1-2.999-3l7.91-7.91a6 6 0 0 1 7.057-8.259c.438.12.54.662.219.984z" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "x",
        group: "chrome",
        body: r##"<path d="M18 6 6 18" /> <path d="m6 6 12 12" />"##,
        fillable: false,
        mirror: false,
    },
    Icon {
        name: "zap",
        group: "technical",
        body: r##"<path d="M15.914 4a1.5 1.5 0 00-2.474-1.561l-9 9A1.5 1.5 0 005.5 14h4.002a.5.5 0 01.471.666L8.086 20a1.5 1.5 0 002.475 1.56l9-9A1.5 1.5 0 0018.5 10h-3.997a.5.5 0 01-.472-.667z" />"##,
        fillable: false,
        mirror: false,
    },
];

/// Every icon name as a constant, so the framework's own uses are
/// checked by the compiler rather than by a test.
pub mod names {
    pub const ACTIVITY: &str = "activity";
    pub const ALARM_CLOCK: &str = "alarm-clock";
    pub const ARROW_UP_DOWN: &str = "arrow-up-down";
    pub const AT_SIGN: &str = "at-sign";
    pub const AWARD: &str = "award";
    pub const BADGE_PERCENT: &str = "badge-percent";
    pub const BANKNOTE: &str = "banknote";
    pub const BELL: &str = "bell";
    pub const BELL_OFF: &str = "bell-off";
    pub const BELL_RING: &str = "bell-ring";
    pub const BLOCKS: &str = "blocks";
    pub const BLUETOOTH: &str = "bluetooth";
    pub const BOLD: &str = "bold";
    pub const BOOK_OPEN: &str = "book-open";
    pub const BOOKMARK: &str = "bookmark";
    pub const BOT: &str = "bot";
    pub const BOX: &str = "box";
    pub const BOXES: &str = "boxes";
    pub const BRACES: &str = "braces";
    pub const BRIEFCASE: &str = "briefcase";
    pub const BRUSH: &str = "brush";
    pub const BUG: &str = "bug";
    pub const BUILDING: &str = "building";
    pub const BUILDING_2: &str = "building-2";
    pub const CALCULATOR: &str = "calculator";
    pub const CALENDAR: &str = "calendar";
    pub const CALENDAR_DAYS: &str = "calendar-days";
    pub const CAMERA: &str = "camera";
    pub const CHART_BAR: &str = "chart-bar";
    pub const CHART_LINE: &str = "chart-line";
    pub const CHART_PIE: &str = "chart-pie";
    pub const CHECK: &str = "check";
    pub const CHECK_CHECK: &str = "check-check";
    pub const CHEVRON_DOWN: &str = "chevron-down";
    pub const CHEVRON_LEFT: &str = "chevron-left";
    pub const CHEVRON_RIGHT: &str = "chevron-right";
    pub const CHEVRON_UP: &str = "chevron-up";
    pub const CHEVRONS_LEFT: &str = "chevrons-left";
    pub const CHEVRONS_RIGHT: &str = "chevrons-right";
    pub const CIRCLE: &str = "circle";
    pub const CIRCLE_ALERT: &str = "circle-alert";
    pub const CIRCLE_CHECK: &str = "circle-check";
    pub const CIRCLE_HELP: &str = "circle-help";
    pub const CIRCLE_X: &str = "circle-x";
    pub const CLOCK: &str = "clock";
    pub const CLOUD: &str = "cloud";
    pub const CLOUD_DOWNLOAD: &str = "cloud-download";
    pub const CLOUD_UPLOAD: &str = "cloud-upload";
    pub const CODE: &str = "code";
    pub const COINS: &str = "coins";
    pub const COLUMNS_3: &str = "columns-3";
    pub const COMPASS: &str = "compass";
    pub const COMPONENT: &str = "component";
    pub const CONTACT: &str = "contact";
    pub const COPY: &str = "copy";
    pub const CPU: &str = "cpu";
    pub const CREDIT_CARD: &str = "credit-card";
    pub const CROWN: &str = "crown";
    pub const DATABASE: &str = "database";
    pub const DOWNLOAD: &str = "download";
    pub const DROPLET: &str = "droplet";
    pub const ELLIPSIS: &str = "ellipsis";
    pub const ELLIPSIS_VERTICAL: &str = "ellipsis-vertical";
    pub const EXTERNAL_LINK: &str = "external-link";
    pub const EYE: &str = "eye";
    pub const EYE_OFF: &str = "eye-off";
    pub const FILE: &str = "file";
    pub const FILE_TEXT: &str = "file-text";
    pub const FILES: &str = "files";
    pub const FILM: &str = "film";
    pub const FINGERPRINT: &str = "fingerprint";
    pub const FLAG: &str = "flag";
    pub const FLAME: &str = "flame";
    pub const FOLDER: &str = "folder";
    pub const FOLDER_OPEN: &str = "folder-open";
    pub const FOLDER_PLUS: &str = "folder-plus";
    pub const FUNNEL: &str = "funnel";
    pub const GAUGE: &str = "gauge";
    pub const GIFT: &str = "gift";
    pub const GIT_BRANCH: &str = "git-branch";
    pub const GLOBE: &str = "globe";
    pub const GRIP_VERTICAL: &str = "grip-vertical";
    pub const HAMMER: &str = "hammer";
    pub const HARD_DRIVE: &str = "hard-drive";
    pub const HEADING: &str = "heading";
    pub const HEART: &str = "heart";
    pub const HISTORY: &str = "history";
    pub const HOME: &str = "home";
    pub const ID_CARD: &str = "id-card";
    pub const IMAGE: &str = "image";
    pub const IMAGES: &str = "images";
    pub const INFO: &str = "info";
    pub const ITALIC: &str = "italic";
    pub const KEY: &str = "key";
    pub const LANDMARK: &str = "landmark";
    pub const LAPTOP: &str = "laptop";
    pub const LAYERS: &str = "layers";
    pub const LAYOUT_DASHBOARD: &str = "layout-dashboard";
    pub const LAYOUT_GRID: &str = "layout-grid";
    pub const LAYOUT_TEMPLATE: &str = "layout-template";
    pub const LEAF: &str = "leaf";
    pub const LIGHTBULB: &str = "lightbulb";
    pub const LINK: &str = "link";
    pub const LIST: &str = "list";
    pub const LIST_ORDERED: &str = "list-ordered";
    pub const LOADER_CIRCLE: &str = "loader-circle";
    pub const LOCK: &str = "lock";
    pub const LOCK_OPEN: &str = "lock-open";
    pub const LOG_IN: &str = "log-in";
    pub const LOG_OUT: &str = "log-out";
    pub const MAIL: &str = "mail";
    pub const MAP: &str = "map";
    pub const MAP_PIN: &str = "map-pin";
    pub const MAP_PINNED: &str = "map-pinned";
    pub const MEGAPHONE: &str = "megaphone";
    pub const MENU: &str = "menu";
    pub const MESSAGE_CIRCLE: &str = "message-circle";
    pub const MESSAGE_SQUARE: &str = "message-square";
    pub const MIC: &str = "mic";
    pub const MONITOR: &str = "monitor";
    pub const MOON: &str = "moon";
    pub const MUSIC: &str = "music";
    pub const NAVIGATION: &str = "navigation";
    pub const NEWSPAPER: &str = "newspaper";
    pub const NOTEBOOK_PEN: &str = "notebook-pen";
    pub const NOTEPAD_TEXT: &str = "notepad-text";
    pub const PACKAGE: &str = "package";
    pub const PAINTBRUSH: &str = "paintbrush";
    pub const PALETTE: &str = "palette";
    pub const PANEL_LEFT: &str = "panel-left";
    pub const PAPERCLIP: &str = "paperclip";
    pub const PENCIL: &str = "pencil";
    pub const PERCENT: &str = "percent";
    pub const PHONE: &str = "phone";
    pub const PIN: &str = "pin";
    pub const PLUG: &str = "plug";
    pub const PLUS: &str = "plus";
    pub const PRINTER: &str = "printer";
    pub const PUZZLE: &str = "puzzle";
    pub const QR_CODE: &str = "qr-code";
    pub const QUOTE: &str = "quote";
    pub const RECEIPT: &str = "receipt";
    pub const REDO_2: &str = "redo-2";
    pub const REFRESH_CW: &str = "refresh-cw";
    pub const ROCKET: &str = "rocket";
    pub const RSS: &str = "rss";
    pub const SAVE: &str = "save";
    pub const SCALE: &str = "scale";
    pub const SEARCH: &str = "search";
    pub const SEND: &str = "send";
    pub const SERVER: &str = "server";
    pub const SETTINGS: &str = "settings";
    pub const SHIELD: &str = "shield";
    pub const SHIELD_CHECK: &str = "shield-check";
    pub const SHOPPING_BAG: &str = "shopping-bag";
    pub const SHOPPING_CART: &str = "shopping-cart";
    pub const SLIDERS_HORIZONTAL: &str = "sliders-horizontal";
    pub const SMARTPHONE: &str = "smartphone";
    pub const SPARKLES: &str = "sparkles";
    pub const SQUARE: &str = "square";
    pub const SQUARE_CHECK: &str = "square-check";
    pub const SQUARE_PEN: &str = "square-pen";
    pub const STAR: &str = "star";
    pub const STORE: &str = "store";
    pub const SUN: &str = "sun";
    pub const TABLET: &str = "tablet";
    pub const TAG: &str = "tag";
    pub const TAGS: &str = "tags";
    pub const TARGET: &str = "target";
    pub const TERMINAL: &str = "terminal";
    pub const TICKET: &str = "ticket";
    pub const TIMER: &str = "timer";
    pub const TRASH_2: &str = "trash-2";
    pub const TRENDING_DOWN: &str = "trending-down";
    pub const TRENDING_UP: &str = "trending-up";
    pub const TRIANGLE: &str = "triangle";
    pub const TRIANGLE_ALERT: &str = "triangle-alert";
    pub const TROPHY: &str = "trophy";
    pub const TRUCK: &str = "truck";
    pub const TYPE: &str = "type";
    pub const UNDERLINE: &str = "underline";
    pub const UNDO_2: &str = "undo-2";
    pub const UNLINK: &str = "unlink";
    pub const UPLOAD: &str = "upload";
    pub const USER: &str = "user";
    pub const USER_PLUS: &str = "user-plus";
    pub const USER_ROUND: &str = "user-round";
    pub const USERS: &str = "users";
    pub const VIDEO: &str = "video";
    pub const WALLET: &str = "wallet";
    pub const WAND_SPARKLES: &str = "wand-sparkles";
    pub const WEBHOOK: &str = "webhook";
    pub const WIFI: &str = "wifi";
    pub const WORKFLOW: &str = "workflow";
    pub const WRENCH: &str = "wrench";
    pub const X: &str = "x";
    pub const ZAP: &str = "zap";
}
